import "./globals.css";
import type { Metadata } from "next";
import { Prata } from "next/font/google";
import NavbarMobile from "@/components/NavbarMobile";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import DoctolibStick from "@/components/DoctolibStick";

const prata = Prata({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-prata",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${prata.variable} w-screen h-screen overflow-x-hidden`}>
        <Navbar />
        <NavbarMobile />
        <DoctolibStick />
        {children}
        <Footer />
      </body>
    </html>
  );
}
